/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author 22156
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    
    private Point initialClick;
    
    public MainGUI() {
        initComponents();
        
        javax.swing.Timer timer = new javax.swing.Timer(1000, (java.awt.event.ActionEvent evt) -> { // updates every second
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss"); // format for the clock
            String currentTime = sdf.format(new Date()); // define clock
            Clock.setText(currentTime); // clock
        });
        timer.start();
        
        ImageIcon icon = new ImageIcon("C:\\Users\\22156\\OneDrive - northcote.school.nz\\Documents\\NetBeansProjects\\javaguibad\\src\\GUI\\Images\\desktop.png");
        setIconImage(icon.getImage());
        
        styleButton(startBtn);
        styleButton(calculatorBtn);
        styleButton(notepadBtn);
        styleButton(paintBtn);
        styleButton(musicBtn);
        styleButton(wallpaperBtn);
        
        styleTextField(Clock);
        
        // to do: Apply calculator drag logic to all apps
        //        Make apps closeable
        //        Check if app is open, raise app isntead of opening if its open.
        //        Make apps frfr
        
        CalcTitlebar.addMouseListener(new MouseAdapter() { // adds mouse checking to calculator
            @Override
            public void mousePressed(MouseEvent e) {
                initialClick = e.getPoint();
            }
        });

        CalcTitlebar.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                int thisX = Calculator.getLocation().x; // gets X and Y
                int thisY = Calculator.getLocation().y;

                int xMoved = e.getX() - initialClick.x; // checks mouse movement when held
                int yMoved = e.getY() - initialClick.y;

                int X = thisX + xMoved; // gets new position
                int Y = thisY + yMoved;
                
                int parentWidth = getContentPane().getWidth(); // make sure it doesnt go off screen
                int parentHeight = getContentPane().getHeight();
                int calcWidth = Calculator.getWidth();
                int calcHeight = Calculator.getHeight();
                X = Math.max(0, Math.min(X, parentWidth - calcWidth));
                Y = Math.max(0, Math.min(Y, parentHeight - calcHeight));

                Calculator.setLocation(X, Y); // moves calculator
            }
        });
    }
    
    private void styleButton(javax.swing.JButton button) { // Styling for the buttons
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setFocusPainted(false);
        button.setOpaque(false);
    }
    
    private void styleTextField(javax.swing.JTextField textField) { // Styling for the text field
        textField.setBorder(null);
        textField.setFocusable(false);
    }

    private String[] wallpapers = {"/GUI/Images/Wall1.jpg", "/GUI/Images/Wall2.jpg", "/GUI/Images/Wall3.jpg"};
    private int currentWallpaper = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calculator = new javax.swing.JPanel();
        CalcTitlebar = new javax.swing.JPanel();
        CalcTitle = new javax.swing.JLabel();
        CalcClose = new javax.swing.JButton();
        CalcField = new javax.swing.JTextField();
        CalcEquals = new javax.swing.JButton();
        CalcClear = new javax.swing.JButton();
        CalcPlus = new javax.swing.JButton();
        CalcMinus = new javax.swing.JButton();
        CalcMulti = new javax.swing.JButton();
        CalcDiv = new javax.swing.JButton();
        CalcMod = new javax.swing.JButton();
        CalcPeriod = new javax.swing.JButton();
        CalcPower = new javax.swing.JButton();
        Calc0 = new javax.swing.JButton();
        Calc1 = new javax.swing.JButton();
        Calc2 = new javax.swing.JButton();
        Calc3 = new javax.swing.JButton();
        Calc4 = new javax.swing.JButton();
        Calc5 = new javax.swing.JButton();
        Calc6 = new javax.swing.JButton();
        Calc7 = new javax.swing.JButton();
        Calc8 = new javax.swing.JButton();
        Calc9 = new javax.swing.JButton();
        Taskbar = new javax.swing.JPanel();
        startBtn = new javax.swing.JButton();
        calculatorBtn = new javax.swing.JButton();
        notepadBtn = new javax.swing.JButton();
        paintBtn = new javax.swing.JButton();
        wallpaperBtn = new javax.swing.JButton();
        Clock = new javax.swing.JTextField();
        musicBtn = new javax.swing.JButton();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desktop");
        setResizable(false);
        setSize(new java.awt.Dimension(1368, 770));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Calculator.setBackground(new java.awt.Color(102, 102, 102));

        CalcTitlebar.setBackground(new java.awt.Color(51, 51, 51));
        CalcTitlebar.setForeground(new java.awt.Color(51, 51, 51));

        CalcTitle.setBackground(new java.awt.Color(255, 255, 255));
        CalcTitle.setForeground(new java.awt.Color(255, 255, 255));
        CalcTitle.setText("Calculator");

        CalcClose.setText("X");

        javax.swing.GroupLayout CalcTitlebarLayout = new javax.swing.GroupLayout(CalcTitlebar);
        CalcTitlebar.setLayout(CalcTitlebarLayout);
        CalcTitlebarLayout.setHorizontalGroup(
            CalcTitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalcTitlebarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(CalcTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CalcClose, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CalcTitlebarLayout.setVerticalGroup(
            CalcTitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalcTitlebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalcTitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalcTitle)
                    .addComponent(CalcClose))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        CalcEquals.setText("=");

        CalcClear.setText("Clear");

        CalcPlus.setText("+");

        CalcMinus.setText("-");

        CalcMulti.setText("X");

        CalcDiv.setText("/");

        CalcMod.setText("M");

        CalcPeriod.setText(".");

        CalcPower.setText("^");

        Calc0.setText("0");

        Calc1.setText("1");

        Calc2.setText("2");

        Calc3.setText("3");

        Calc4.setText("4");

        Calc5.setText("5");
        Calc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc5ActionPerformed(evt);
            }
        });

        Calc6.setText("6");

        Calc7.setText("7");

        Calc8.setText("8");

        Calc9.setText("9");

        javax.swing.GroupLayout CalculatorLayout = new javax.swing.GroupLayout(Calculator);
        Calculator.setLayout(CalculatorLayout);
        CalculatorLayout.setHorizontalGroup(
            CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalcTitlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatorLayout.createSequentialGroup()
                        .addComponent(CalcField)
                        .addGap(18, 18, 18)
                        .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CalcMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CalcMinus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(CalcPlus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(CalcMulti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CalcDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CalculatorLayout.createSequentialGroup()
                        .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalculatorLayout.createSequentialGroup()
                                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Calc0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Calc7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Calc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Calc4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Calc2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CalcPeriod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Calc5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Calc8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(CalcClear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalculatorLayout.createSequentialGroup()
                                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Calc3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(CalcPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Calc9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(Calc6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 79, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(CalcEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, 16))
        );
        CalculatorLayout.setVerticalGroup(
            CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorLayout.createSequentialGroup()
                .addComponent(CalcTitlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalcMod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CalculatorLayout.createSequentialGroup()
                            .addComponent(CalcDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CalcMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CalcMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CalcPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CalculatorLayout.createSequentialGroup()
                            .addComponent(Calc7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(Calc0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorLayout.createSequentialGroup()
                        .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Calc8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Calc9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Calc5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Calc4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Calc6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Calc2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Calc1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CalcPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorLayout.createSequentialGroup()
                        .addComponent(Calc3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CalcPower, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalcClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(Calculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 400));

        Taskbar.setBackground(new java.awt.Color(0, 0, 0));
        Taskbar.setForeground(new java.awt.Color(255, 255, 255));

        startBtn.setBackground(new java.awt.Color(0, 0, 0));
        startBtn.setForeground(new java.awt.Color(0, 0, 0));
        startBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/start.png"))); // NOI18N
        startBtn.setToolTipText("");
        startBtn.setBorder(null);
        startBtn.setBorderPainted(false);
        startBtn.setMaximumSize(new java.awt.Dimension(110, 111));
        startBtn.setPreferredSize(new java.awt.Dimension(110, 111));
        startBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/startclick.png"))); // NOI18N
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        calculatorBtn.setBackground(new java.awt.Color(0, 0, 0));
        calculatorBtn.setForeground(new java.awt.Color(255, 255, 255));
        calculatorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/calc.png"))); // NOI18N
        calculatorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorBtnActionPerformed(evt);
            }
        });

        notepadBtn.setBackground(new java.awt.Color(0, 0, 0));
        notepadBtn.setForeground(new java.awt.Color(255, 255, 255));
        notepadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/notepad.png"))); // NOI18N
        notepadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notepadBtnActionPerformed(evt);
            }
        });

        paintBtn.setBackground(new java.awt.Color(0, 0, 0));
        paintBtn.setForeground(new java.awt.Color(255, 255, 255));
        paintBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/paint.png"))); // NOI18N
        paintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintBtnActionPerformed(evt);
            }
        });

        wallpaperBtn.setBackground(new java.awt.Color(0, 0, 0));
        wallpaperBtn.setForeground(new java.awt.Color(255, 255, 255));
        wallpaperBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/wallpaper.png"))); // NOI18N
        wallpaperBtn.setText("Change Wallpaper");
        wallpaperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wallpaperBtnActionPerformed(evt);
            }
        });

        Clock.setEditable(false);
        Clock.setBackground(new java.awt.Color(0, 0, 0));
        Clock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clock.setForeground(new java.awt.Color(255, 255, 255));
        Clock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Clock.setText("Loading");
        Clock.setAutoscrolls(false);
        Clock.setMaximumSize(new java.awt.Dimension(68, 26));
        Clock.setOpaque(true);
        Clock.setPreferredSize(new java.awt.Dimension(68, 26));
        Clock.setSelectionColor(new java.awt.Color(255, 255, 255));
        Clock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClockActionPerformed(evt);
            }
        });

        musicBtn.setBackground(new java.awt.Color(0, 0, 0));
        musicBtn.setForeground(new java.awt.Color(255, 255, 255));
        musicBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/music.png"))); // NOI18N

        javax.swing.GroupLayout TaskbarLayout = new javax.swing.GroupLayout(Taskbar);
        Taskbar.setLayout(TaskbarLayout);
        TaskbarLayout.setHorizontalGroup(
            TaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calculatorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notepadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(musicBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 862, Short.MAX_VALUE)
                .addComponent(wallpaperBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Clock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        TaskbarLayout.setVerticalGroup(
            TaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(musicBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paintBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notepadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calculatorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TaskbarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Clock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wallpaperBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Taskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1370, 50));

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Wall1.jpg"))); // NOI18N
        Wallpaper.setMaximumSize(new java.awt.Dimension(1366, 770));
        Wallpaper.setMinimumSize(new java.awt.Dimension(1366, 770));
        Wallpaper.setPreferredSize(new java.awt.Dimension(1366, 770));
        getContentPane().add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_startBtnActionPerformed

    private void paintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintBtnActionPerformed

    private void notepadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notepadBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notepadBtnActionPerformed

    private void calculatorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculatorBtnActionPerformed

    private void wallpaperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wallpaperBtnActionPerformed
        currentWallpaper = (currentWallpaper + 1) % wallpapers.length;
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource(wallpapers[currentWallpaper])));
    }//GEN-LAST:event_wallpaperBtnActionPerformed

    private void ClockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClockActionPerformed

    private void Calc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Calc5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calc0;
    private javax.swing.JButton Calc1;
    private javax.swing.JButton Calc2;
    private javax.swing.JButton Calc3;
    private javax.swing.JButton Calc4;
    private javax.swing.JButton Calc5;
    private javax.swing.JButton Calc6;
    private javax.swing.JButton Calc7;
    private javax.swing.JButton Calc8;
    private javax.swing.JButton Calc9;
    private javax.swing.JButton CalcClear;
    private javax.swing.JButton CalcClose;
    private javax.swing.JButton CalcDiv;
    private javax.swing.JButton CalcEquals;
    private javax.swing.JTextField CalcField;
    private javax.swing.JButton CalcMinus;
    private javax.swing.JButton CalcMod;
    private javax.swing.JButton CalcMulti;
    private javax.swing.JButton CalcPeriod;
    private javax.swing.JButton CalcPlus;
    private javax.swing.JButton CalcPower;
    private javax.swing.JLabel CalcTitle;
    private javax.swing.JPanel CalcTitlebar;
    private javax.swing.JPanel Calculator;
    private javax.swing.JTextField Clock;
    private javax.swing.JPanel Taskbar;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton calculatorBtn;
    private javax.swing.JButton musicBtn;
    private javax.swing.JButton notepadBtn;
    private javax.swing.JButton paintBtn;
    private javax.swing.JButton startBtn;
    private javax.swing.JButton wallpaperBtn;
    // End of variables declaration//GEN-END:variables
}
